catalyst-item: "ENDER_EYE"
portal-width: 3
portal-height: 4
destination-world: "backrooms_level0"
spawn:
  x: 0.5
  y: 64
  z: 0.5
  yaw: 0.0
  pitch: 0.0
transition:
  fade-ticks: 40
  sound: "block.end_portal.spawn"
