name: CustomPortals
version: ${version}
main: me.mapacheee.customportals.CustomPortalsPlugin
api-version: '1.21'
description: Portal a los Backrooms con efectos visuales
author: Mapacheee
folia-supported: true
dependencies:
  server:
    MapacheeeLib:
      load: BEFORE
      required: true
